<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ASDLAPKCH0119" failures="1" tests="21" name="com.saucedemo.tests.ProductTest" time="29.381" errors="2" timestamp="2023-10-12T15:06:30 IST" skipped="0">
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC014_sortDescendingOrder" time="2.561"/>
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC015_sortLowToHigh" time="0.517"/>
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC016_sortHighToLow" time="0.554"/>
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC013_sortAscendingOrder" time="0.527"/>
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC008_addToCart" time="0.250"/>
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC009_addToAllCart" time="3.010"/>
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC012_deSelectAddToCart" time="1.245"/>
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC017_verifyShoppingCartButton" time="0.249"/>
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC018_verifyRemoveButton" time="2.291"/>
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC019_verifyCheckoutButton" time="0.272"/>
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC020_verifyContinueShoppingButton" time="0.091"/>
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC021_verifyCancelButton" time="0.029"/>
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC022_verifyContinueButtonWithoutFirstName" time="3.346"/>
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC023_verifyContinueButtonWithoutLastName" time="2.269">
    <error message="Keys to send should be a not null CharSequence" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:97)
at com.saucedemo.pages.CheckOutInfoPage.verifyCart(CheckOutInfoPage.java:22)
at com.saucedemo.tests.ProductTest.TC023_verifyContinueButtonWithoutLastName(ProductTest.java:167)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC023_verifyContinueButtonWithoutLastName -->
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC024_verifyContinueButtonWithoutPostalCode" time="2.255">
    <error message="Keys to send should be a not null CharSequence" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:97)
at com.saucedemo.pages.CheckOutInfoPage.verifyCart(CheckOutInfoPage.java:23)
at com.saucedemo.tests.ProductTest.TC024_verifyContinueButtonWithoutPostalCode(ProductTest.java:178)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC024_verifyContinueButtonWithoutPostalCode -->
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC025_verifyContinueButtonWithAllDetails" time="5.568"/>
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC027_verifyCancelButtonInCheckoutPage" time="0.020"/>
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC026_verifyFinishButtonInCheckoutPage" time="0.250"/>
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC007_navigateBrowserBack" time="2.037"/>
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC006_navigateBrowserForward" time="2.022"/>
  <testcase classname="com.saucedemo.tests.ProductTest" name="TC030_verifyThankYouMessageInOverviewPage" time="0.018">
    <failure message="expected [Thank you for your order!] but found [[[FirefoxDriver: firefox on windows (cdc02391-e596-4e8b-b280-37ac50f5f86f)] -&gt; xpath: //h2[contains(text(),&#039;Thank you for your order!&#039;)]]]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Thank you for your order!] but found [[[FirefoxDriver: firefox on windows (cdc02391-e596-4e8b-b280-37ac50f5f86f)] -> xpath: //h2[contains(text(),'Thank you for your order!')]]]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:644)
at com.saucedemo.keywords.Keywords.assertEquals(Keywords.java:230)
at com.saucedemo.pages.CompletePage.verifyThankYouMessage(CompletePage.java:17)
at com.saucedemo.tests.ProductTest.TC030_verifyThankYouMessageInOverviewPage(ProductTest.java:220)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC030_verifyThankYouMessageInOverviewPage -->
</testsuite> <!-- com.saucedemo.tests.ProductTest -->
